services:
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8083"
    volumes:
      - .:/app
    ports:
      - "8083:8083"  # Настраиваем внешний порт 8083
    depends_on:
      - db
    environment:
      DJANGO_ALLOWED_HOSTS: "0.0.0.0,localhost,127.0.0.1"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
    command: celery -A kursach worker --loglevel=info
    depends_on:
      - web
      - redis
      - db
    environment:
      DJANGO_SETTINGS_MODULE: "kursach.settings"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
volumes:
  postgres_data:
