# Generated by Django 5.1.2 on 2024-10-20 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0002_alter_booking_booking_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 14, 42, 52, 848086, tzinfo=datetime.timezone.utc)),
        ),
    ]
