# Generated by Django 5.1.2 on 2024-10-23 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0003_alter_booking_booking_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 18, 39, 16, 747720, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Ожидает подтверждения'), ('Confirmed', 'Подтверждено'), ('Cancelled', 'Отменено')], default='Pending', max_length=20),
        ),
    ]
