# Generated by Django 5.1.2 on 2024-10-23 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0006_alter_booking_booking_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 18, 55, 40, 764189, tzinfo=datetime.timezone.utc)),
        ),
    ]
