# Generated by Django 5.1.2 on 2024-10-23 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0007_alter_booking_booking_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningtable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 19, 42, 55, 782987, tzinfo=datetime.timezone.utc)),
        ),
    ]
