# Generated by Django 5.1.2 on 2024-11-03 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0008_diningtable_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Посетитель', 'verbose_name_plural': 'Посетители'},
        ),
        migrations.AlterModelOptions(
            name='diningtable',
            options={'verbose_name': 'Стол', 'verbose_name_plural': 'Столы'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 18, 27, 2, 862098, tzinfo=datetime.timezone.utc)),
        ),
    ]
