# Generated by Django 5.1.2 on 2024-11-03 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0010_booking_duration_of_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 19, 37, 26, 856533, tzinfo=datetime.timezone.utc)),
        ),
    ]
