# Generated by Django 5.1.2 on 2024-11-04 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0016_alter_booking_booking_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 11, 6, 34, 531522, tzinfo=datetime.timezone.utc)),
        ),
    ]
