# Generated by Django 5.1.2 on 2024-11-05 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0017_alter_booking_booking_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 21, 25, 18, 727976, tzinfo=datetime.timezone.utc)),
        ),
    ]
